# Generated by Django 5.0.6 on 2024-06-17 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_player_position_alter_player_team_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='element_type',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(max_length=10),
        ),
    ]
