# Generated by Django 5.0.6 on 2024-06-18 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_player_total_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='position',
        ),
        migrations.AddField(
            model_name='player',
            name='assists',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='bps',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='clean_sheets',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='creativity',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='player',
            name='goals_conceded',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='goals_scored',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='ict_index',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='player',
            name='influence',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='player',
            name='minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='own_goals',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='penalties_missed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='penalties_saved',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='red_cards',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='saves',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='threat',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='player',
            name='yellow_cards',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='element_type',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='player',
            name='price',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
