# Generated by Django 5.0.6 on 2024-06-25 18:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_player_position_player_assists_player_bonus_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gameweek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=50)),
                ('deadline_time', models.DateTimeField()),
                ('average_entry_score', models.IntegerField(blank=True, null=True)),
                ('highest_score', models.IntegerField(blank=True, null=True)),
                ('is_previous', models.BooleanField(default=False)),
                ('is_current', models.BooleanField(default=False)),
                ('is_next', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Squad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget', models.DecimalField(decimal_places=1, default=100.0, max_digits=8)),
                ('wildcard_used', models.IntegerField(default=0)),
                ('bench_boost_used', models.BooleanField(default=False)),
                ('free_hit_used', models.BooleanField(default=False)),
                ('transfers_available', models.IntegerField(default=1)),
                ('last_transfer_gameweek', models.IntegerField(default=0)),
                ('captain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='captain', to='api.player')),
                ('players', models.ManyToManyField(related_name='squads', to='api.player')),
                ('starting_lineup', models.ManyToManyField(related_name='starting_lineup', to='api.player')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameweek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.gameweek')),
                ('player_in', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_in', to='api.player')),
                ('player_out', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_out', to='api.player')),
                ('squad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='api.squad')),
            ],
        ),
    ]
