# Generated by Django 5.0.6 on 2024-06-25 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_player_price_alter_team_name_squad'),
    ]

    operations = [
        migrations.AddField(
            model_name='squad',
            name='bench_boost_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='squad',
            name='captain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='captain', to='api.player'),
        ),
        migrations.AddField(
            model_name='squad',
            name='free_hit_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='squad',
            name='starting_lineup',
            field=models.ManyToManyField(related_name='starting_lineup', to='api.player'),
        ),
        migrations.AddField(
            model_name='squad',
            name='wildcard_used',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='squad',
            name='players',
            field=models.ManyToManyField(related_name='squads', to='api.player'),
        ),
    ]
