# Generated by Django 5.0.6 on 2024-06-25 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_squad_bench_boost_used_squad_captain_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gameweek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=50)),
                ('deadline_time', models.DateTimeField()),
                ('average_entry_score', models.IntegerField(blank=True, null=True)),
                ('highest_score', models.IntegerField(blank=True, null=True)),
                ('is_previous', models.BooleanField(default=False)),
                ('is_current', models.BooleanField(default=False)),
                ('is_next', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='squad',
            name='last_transfer_gameweek',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='squad',
            name='transfers_available',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameweek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.gameweek')),
                ('player_in', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_in', to='api.player')),
                ('player_out', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_out', to='api.player')),
                ('squad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='api.squad')),
            ],
        ),
    ]
